"""Resolve persisted unit dependencies to immutable Croco Guided request facts."""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path
from typing import Any

from lib.generation_queue import get_generation_queue
from lib.providers import PROVIDER_CROCO
from lib.version_manager import VersionManager
from lib.video_backends.base import VideoContinuationGuide
from lib.video_dependency import dependency_source_unit_id


async def resolve_video_continuation_guide(
    *,
    project_path: Path,
    unit: Mapping[str, Any],
    resource_type: str,
    user_id: str,
) -> tuple[VideoContinuationGuide | None, dict[str, object] | None]:
    """Resolve the selected source version to its succeeded provider job.

    Manually uploaded or historical versions without execution provenance are
    deliberately rejected: a local mp4 path is not evidence that the GPU still
    has the verified original output required by ``add_guide``.
    """

    source_unit_id = dependency_source_unit_id(unit)
    if source_unit_id is None:
        return None, None
    dependency = unit.get("video_dependency")
    assert isinstance(dependency, Mapping)
    if dependency.get("relation") != "continuation":
        raise ValueError(f"unsupported video dependency relation for {source_unit_id}")
    audio_policy = dependency.get("audio_policy", "none")
    if audio_policy not in {"none", "continue"}:
        raise ValueError(f"unsupported video dependency audio_policy for {source_unit_id}")

    version_info = VersionManager(project_path).get_versions(resource_type, source_unit_id)
    current_version = version_info.get("current_version")
    selected = next(
        (
            item
            for item in version_info.get("versions") or []
            if isinstance(item, dict) and item.get("version") == current_version
        ),
        None,
    )
    if not isinstance(selected, dict):
        raise ValueError(f"dependency {source_unit_id} has no selected generated video version")
    execution_task_id = selected.get("execution_task_id")
    if not isinstance(execution_task_id, str) or not execution_task_id:
        raise ValueError(
            f"dependency {source_unit_id} selected version has no GPU execution provenance; regenerate it first"
        )
    if selected.get("execution_provider_id") != PROVIDER_CROCO:
        raise ValueError(f"dependency {source_unit_id} selected version was not generated by Croco H3")

    source_task = await get_generation_queue().get_task(execution_task_id, user_id=user_id)
    if not isinstance(source_task, dict) or source_task.get("status") != "succeeded":
        raise ValueError(f"dependency {source_unit_id} source task is not succeeded")
    if source_task.get("provider_id") != PROVIDER_CROCO:
        raise ValueError(f"dependency {source_unit_id} source task provider is not Croco")
    source_job_id = source_task.get("provider_job_id")
    if not isinstance(source_job_id, str) or not source_job_id:
        raise ValueError(f"dependency {source_unit_id} source task has no GPU job ID")

    guide = VideoContinuationGuide(
        source_job_id=source_job_id,
        include_guide_audio=audio_policy == "continue",
    )
    evidence: dict[str, object] = {
        "source_unit_id": source_unit_id,
        "relation": "continuation",
        "audio_policy": audio_policy,
        "source_version": current_version,
        "source_execution_task_id": execution_task_id,
        "guide_frames": guide.guide_frames,
        "source_media": guide.source_media,
    }
    return guide, evidence


__all__ = ["resolve_video_continuation_guide"]
