create extension if not exists pgcrypto with schema extensions;

create table if not exists public.arcreel_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null,
  auth_email text not null unique,
  display_name text,
  role text not null default 'user' check (role in ('admin', 'user')),
  status text not null default 'active' check (status in ('active', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint arcreel_profiles_username_format_check
    check (username ~ '^[A-Za-z0-9][A-Za-z0-9._-]{1,63}$')
);

create unique index if not exists arcreel_profiles_username_lower_unique
  on public.arcreel_profiles (lower(username));

create table if not exists public.arcreel_provider_credentials (
  id uuid primary key default extensions.gen_random_uuid(),
  user_id uuid not null references public.arcreel_profiles(id) on delete cascade,
  provider_id text not null check (provider_id ~ '^[a-z0-9][a-z0-9._-]{0,63}$'),
  encrypted_payload text not null,
  masked_hint jsonb not null default '{}'::jsonb,
  revision bigint not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, provider_id)
);

create index if not exists arcreel_provider_credentials_user_id_idx
  on public.arcreel_provider_credentials (user_id);

create or replace function public.arcreel_set_updated_at()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists arcreel_profiles_set_updated_at on public.arcreel_profiles;
create trigger arcreel_profiles_set_updated_at before update on public.arcreel_profiles
for each row execute function public.arcreel_set_updated_at();

drop trigger if exists arcreel_provider_credentials_set_updated_at on public.arcreel_provider_credentials;
create trigger arcreel_provider_credentials_set_updated_at before update on public.arcreel_provider_credentials
for each row execute function public.arcreel_set_updated_at();

alter table public.arcreel_profiles enable row level security;
alter table public.arcreel_provider_credentials enable row level security;
revoke all on public.arcreel_profiles from anon, authenticated;
revoke all on public.arcreel_provider_credentials from anon, authenticated;
grant all on public.arcreel_profiles to service_role;
grant all on public.arcreel_provider_credentials to service_role;

comment on table public.arcreel_profiles is
  'ArcReel cloud identities. The UUID is the only durable identity used by local installations.';
comment on column public.arcreel_profiles.auth_email is
  'Internal Supabase Auth email generated by the admin function; never shown as the login name.';
comment on column public.arcreel_provider_credentials.encrypted_payload is
  'AES-GCM encrypted JSON. Decryption is only performed inside ArcReel Edge Functions.';
