create table if not exists public.arcreel_asset_file_deletions (
  id bigint generated by default as identity primary key,
  asset_id uuid not null,
  bucket_id text not null,
  object_path text not null,
  requested_by uuid references public.arcreel_profiles(id) on delete set null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'succeeded')),
  attempt_count integer not null default 0 check (attempt_count >= 0),
  worker_id text,
  last_error text,
  next_attempt_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (bucket_id, object_path)
);

create index if not exists arcreel_asset_file_deletions_pending_idx
  on public.arcreel_asset_file_deletions (next_attempt_at, id)
  where status in ('pending', 'processing');

drop trigger if exists arcreel_asset_file_deletions_set_updated_at
  on public.arcreel_asset_file_deletions;
create trigger arcreel_asset_file_deletions_set_updated_at
before update on public.arcreel_asset_file_deletions
for each row execute function public.arcreel_set_updated_at();

alter table public.arcreel_asset_file_deletions enable row level security;
revoke all on public.arcreel_asset_file_deletions from anon, authenticated;
grant all on public.arcreel_asset_file_deletions to service_role;
grant usage, select on sequence public.arcreel_asset_file_deletions_id_seq to service_role;

create or replace function public.arcreel_admin_list_assets(
  p_asset_type text default null,
  p_origin text default null,
  p_query text default null,
  p_limit integer default 24,
  p_offset integer default 0
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_query text := nullif(btrim(p_query), '');
  v_items jsonb;
  v_total integer;
  v_totals jsonb;
begin
  v_user_id := public.arcreel_require_admin_profile();
  if p_asset_type is not null and p_asset_type not in ('character', 'scene', 'prop') then
    raise exception 'ARCREEL_ASSET_TYPE_INVALID' using errcode = '22023';
  end if;
  if p_origin is not null and p_origin not in ('official', 'user_shared') then
    raise exception 'ARCREEL_ASSET_ORIGIN_INVALID' using errcode = '22023';
  end if;
  if p_limit not between 1 and 100 or p_offset < 0 or char_length(coalesce(v_query, '')) > 200 then
    raise exception 'ARCREEL_ASSET_QUERY_INVALID' using errcode = '22023';
  end if;

  select count(*)::integer
    into v_total
  from public.arcreel_assets a
  where (p_asset_type is null or a.asset_type = p_asset_type)
    and (p_origin is null or a.origin = p_origin)
    and (v_query is null or position(lower(v_query) in lower(a.name)) > 0);

  select jsonb_build_object(
    'character', count(*) filter (where a.asset_type = 'character'),
    'scene', count(*) filter (where a.asset_type = 'scene'),
    'prop', count(*) filter (where a.asset_type = 'prop')
  )
    into v_totals
  from public.arcreel_assets a
  where (p_origin is null or a.origin = p_origin)
    and (v_query is null or position(lower(v_query) in lower(a.name)) > 0);

  select coalesce(jsonb_agg(item.payload order by item.updated_at desc, item.id), '[]'::jsonb)
    into v_items
  from (
    select
      a.id,
      a.updated_at,
      jsonb_build_object(
        'id', a.id,
        'asset_type', a.asset_type,
        'origin', a.origin,
        'status', a.status,
        'version', a.current_version,
        'name', a.name,
        'description', a.description,
        'owner_name', p.username,
        'source_name', s.display_name,
        'created_at', a.created_at,
        'updated_at', a.updated_at,
        'files', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'id', f.id,
              'key', f.file_key,
              'role', f.role,
              'media_type', f.media_type,
              'mime_type', f.mime_type,
              'bucket_id', f.bucket_id,
              'object_path', f.object_path,
              'byte_size', f.byte_size,
              'sha256', f.sha256,
              'revision', f.revision,
              'sort_order', f.sort_order,
              'source_fields', f.source_fields
            ) order by f.sort_order, f.file_key
          )
          from public.arcreel_asset_files f
          join public.arcreel_asset_versions v on v.id = f.version_id
          where v.asset_id = a.id and v.version = a.current_version
        ), '[]'::jsonb)
      ) as payload
    from public.arcreel_assets a
    left join public.arcreel_profiles p on p.id = a.owner_id
    left join public.arcreel_asset_sync_sources s on s.id = a.source_id
    where (p_asset_type is null or a.asset_type = p_asset_type)
      and (p_origin is null or a.origin = p_origin)
      and (v_query is null or position(lower(v_query) in lower(a.name)) > 0)
    order by a.updated_at desc, a.id
    limit p_limit offset p_offset
  ) item;

  return jsonb_build_object(
    'items', v_items,
    'total', v_total,
    'totals', coalesce(v_totals, '{"character":0,"scene":0,"prop":0}'::jsonb)
  );
end;
$$;

create or replace function public.arcreel_admin_get_asset_preview(p_asset_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_result jsonb;
begin
  v_user_id := public.arcreel_require_admin_profile();
  select jsonb_build_object(
    'bucket_id', f.bucket_id,
    'object_path', f.object_path,
    'mime_type', f.mime_type
  )
    into v_result
  from public.arcreel_assets a
  join public.arcreel_asset_versions v
    on v.asset_id = a.id and v.version = a.current_version
  join public.arcreel_asset_files f on f.version_id = v.id
  where a.id = p_asset_id and f.media_type = 'image'
  order by
    case when f.role in ('primary_image', 'sheet') then 0 else 1 end,
    f.sort_order,
    f.file_key
  limit 1;
  if v_result is null then
    raise exception 'ARCREEL_ASSET_PREVIEW_NOT_FOUND' using errcode = '22023';
  end if;
  return v_result;
end;
$$;

create or replace function public.arcreel_admin_delete_asset(p_asset_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user_id uuid;
  v_asset public.arcreel_assets%rowtype;
  v_file_count integer := 0;
begin
  v_user_id := public.arcreel_require_admin_profile();
  select * into v_asset
  from public.arcreel_assets a
  where a.id = p_asset_id
  for update;
  if not found then
    raise exception 'ARCREEL_ASSET_NOT_FOUND' using errcode = '22023';
  end if;

  insert into public.arcreel_asset_file_deletions (
    asset_id, bucket_id, object_path, requested_by,
    status, attempt_count, worker_id, last_error,
    next_attempt_at, claimed_at, completed_at
  )
  select distinct
    v_asset.id, f.bucket_id, f.object_path, v_user_id,
    'pending', 0, null::text, null::text,
    now(), null::timestamptz, null::timestamptz
  from public.arcreel_asset_files f
  join public.arcreel_asset_versions v on v.id = f.version_id
  where v.asset_id = v_asset.id
  on conflict (bucket_id, object_path) do update set
    asset_id = excluded.asset_id,
    requested_by = excluded.requested_by,
    status = 'pending',
    attempt_count = 0,
    worker_id = null,
    last_error = null,
    next_attempt_at = now(),
    claimed_at = null,
    completed_at = null;
  get diagnostics v_file_count = row_count;

  delete from public.arcreel_assets where id = v_asset.id;
  return jsonb_build_object(
    'asset_id', v_asset.id,
    'name', v_asset.name,
    'asset_type', v_asset.asset_type,
    'origin', v_asset.origin,
    'queued_file_count', v_file_count
  );
end;
$$;

create or replace function public.arcreel_claim_asset_file_deletion(p_worker_id text)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job public.arcreel_asset_file_deletions%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'ARCREEL_SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;
  if nullif(btrim(p_worker_id), '') is null then
    raise exception 'ARCREEL_WORKER_ID_REQUIRED' using errcode = '22023';
  end if;

  select * into v_job
  from public.arcreel_asset_file_deletions d
  where (
      d.status = 'pending' and d.next_attempt_at <= now()
    ) or (
      d.status = 'processing' and d.claimed_at < now() - interval '5 minutes'
    )
  order by d.next_attempt_at, d.id
  limit 1
  for update skip locked;
  if not found then return null; end if;

  update public.arcreel_asset_file_deletions set
    status = 'processing',
    worker_id = p_worker_id,
    attempt_count = attempt_count + 1,
    claimed_at = now()
  where id = v_job.id
  returning * into v_job;
  return to_jsonb(v_job);
end;
$$;

create or replace function public.arcreel_report_asset_file_deletion(
  p_deletion_id bigint,
  p_worker_id text,
  p_succeeded boolean,
  p_error text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job public.arcreel_asset_file_deletions%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'ARCREEL_SERVICE_ROLE_REQUIRED' using errcode = '42501';
  end if;

  update public.arcreel_asset_file_deletions set
    status = case when p_succeeded then 'succeeded' else 'pending' end,
    worker_id = case when p_succeeded then p_worker_id else null end,
    last_error = case when p_succeeded then null else left(coalesce(p_error, 'storage_delete_failed'), 1000) end,
    next_attempt_at = case
      when p_succeeded then next_attempt_at
      else now() + make_interval(secs => least(3600, (5 * power(2, least(attempt_count, 9)))::integer))
    end,
    completed_at = case when p_succeeded then now() else null end
  where id = p_deletion_id and status = 'processing' and worker_id = p_worker_id
  returning * into v_job;
  if not found then
    raise exception 'ARCREEL_FILE_DELETION_NOT_OWNED' using errcode = '42501';
  end if;
  return to_jsonb(v_job);
end;
$$;

revoke all on function public.arcreel_admin_list_assets(text, text, text, integer, integer)
  from public, anon;
revoke all on function public.arcreel_admin_get_asset_preview(uuid)
  from public, anon;
revoke all on function public.arcreel_admin_delete_asset(uuid)
  from public, anon;
revoke all on function public.arcreel_claim_asset_file_deletion(text)
  from public, anon, authenticated;
revoke all on function public.arcreel_report_asset_file_deletion(bigint, text, boolean, text)
  from public, anon, authenticated;

grant execute on function public.arcreel_admin_list_assets(text, text, text, integer, integer)
  to authenticated;
grant execute on function public.arcreel_admin_get_asset_preview(uuid)
  to authenticated;
grant execute on function public.arcreel_admin_delete_asset(uuid)
  to authenticated;
grant execute on function public.arcreel_claim_asset_file_deletion(text)
  to service_role;
grant execute on function public.arcreel_report_asset_file_deletion(bigint, text, boolean, text)
  to service_role;

comment on table public.arcreel_asset_file_deletions is
  'Durable outbox for Storage objects left by hard-deleted company catalog assets.';
comment on function public.arcreel_admin_delete_asset(uuid) is
  'Admin hard delete for central asset metadata; cloud files are removed by the monitor worker outbox.';
